spring:
  main:
    web-application-type: reactive

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bettervse}
    username: ${DATABASE_USERNAME:bettervse}
    password: ${DATABASE_PASSWORD:bettervse}

  r2dbc:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  liquibase:
    enabled: true
    change-log: classpath:/changelog.sql
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  mail:
    default-encoding: UTF-8
    host: ${MAIL_HOST:smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: ${MAIL_TEST_CONNECTION:true}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:true}
          timeout: ${MAIL_TIMEOUT:5000}
          starttls:
            enable: true

server:
  port: ${PORT:8080}
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  issuer: https://better-vse.vrba.dev

springdoc:
  swagger-ui:
    path: /swagger
    show-extensions: true

---

spring:
  config:
    activate:
      on-profile: test

  mail:
    test-connection: false # Email client is mocked in tests
