spring:
  main:
    web-application-type: reactive

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bettervse}
    username: ${DATABASE_USERNAME:bettervse}
    password: ${DATABASE_PASSWORD:bettervse}

  r2dbc:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  liquibase:
    enabled: true
    change-log: classpath:/changelog.sql
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  mail:
    default-encoding: UTF-8
    host: ${MAIL_HOST:smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    protocol: smtp
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true

server:
  port: ${PORT:8080}
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always