spring:
  main:
    web-application-type: reactive

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bettervse}
    username: ${DATABASE_USERNAME:bettervse}
    password: ${DATABASE_PASSWORD:bettervse}

  r2dbc:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  liquibase:
    enabled: true
    change-log: classpath:/changelog.sql
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: ${PORT:8080}
  error:
    include-exception: false
    include-stacktrace: never
    include-message: never
