--liquibase formatted sql

--changeset jirkavrba:create-accounts-table
create table accounts
(
    id                int        not null generated by default as identity primary key,
    username          varchar(6) not null unique,
    verification_code varchar(8) unique
);