--liquibase formatted sql

--changeset jirkavrba:create-accounts-table
create table accounts
(
    id                int        not null generated by default as identity primary key,
    username          varchar(6) not null unique,
    verification_code varchar(8) unique
);

--changeset jirkavrba:add-subjects-and-teachers-tables
create table subjects
(
    id       int          not null generated by default as identity primary key,
    insis_id int          not null unique, -- syllabus.pl?predmet=178191
    code     varchar(6)   not null unique, -- 1FP201
    name     varchar(128) not null         -- Finanční teorie, politika a instituce
);

create table teachers
(
    id       int          not null generated by default as identity primary key,
    insis_id int          not null unique, -- clovek.pl?id=116722
    username varchar(12)  not null unique, -- prod00
    name     varchar(128) not null         -- PhDr. David Anthony Procházka, Ph.D., MBA, MSc
);
